<?php
declare(strict_types=1);

namespace IfCastle\Application\Bootloader\BootManager;

use IfCastle\Application\Bootloader\BootManager\Exceptions\BootloaderException;
use IfCastle\Application\Bootloader\BootManager\Exceptions\PackageAlreadyExists;
use IfCastle\Application\Bootloader\BootManager\Exceptions\PackageNotFound;
use IfCastle\OsUtilities\FileSystem\File;
use IfCastle\OsUtilities\Safe;

class BootManagerByDirectory        implements BootManagerInterface
{
    public function __construct(protected string $bootloaderDir) {}
    
    
    #[\Override]
    public function addBootloader(
        string $componentName,
        array  $bootloaders,
        array  $applications = []
    ): void
    {
        $this->validateComponent($componentName);
        
        $file                       = $this->bootloaderDir.'/'.$componentName.'.ini';
        
        if(file_exists($file)) {
            throw new PackageAlreadyExists($componentName);
        }

        $data = <<<INI
is_active = true
INI;

        foreach ($bootloaders as $bootloader) {
            $data .= 'bootloader[] = "'.$bootloader.'"'.PHP_EOL;
        }

        foreach ($applications as $application) {
            $data .= 'for_application[] = "'.$application.'"'.PHP_EOL;
        }

        File::put($file, $data);
    }
    
    #[\Override]
    public function activateBootloader(string $componentName): void
    {
        $this->validateComponent($componentName);
        
        $file                       = $this->bootloaderDir.'/'.$componentName.'.ini';
        
        if(false === file_exists($file)) {
            throw new PackageNotFound($componentName);
        }
        
        $data                       = parse_ini_file($file, true);
        
        if(false === is_array($data)) {
            throw new BootloaderException('Invalid bootloader file: '.$file);
        }
        
        $data['is_active']          = true;
        
        File::put($file, $this->generateBootloaderContent($data));
    }
    
    #[\Override]
    public function deactivateBootloader(string $componentName): void
    {
        $this->validateComponent($componentName);
        
        $file                       = $this->bootloaderDir.'/'.$componentName.'.ini';
        
        if(false === file_exists($file)) {
            throw new BootloaderException('Bootloader not found: '.$componentName);
        }
        
        $data                       = parse_ini_file($file, true);
        
        if(false === is_array($data)) {
            throw new BootloaderException('Invalid bootloader file: '.$file);
        }
        
        $data['is_active']          = false;
        
        File::put($file, $this->generateBootloaderContent($data));
    }
    
    #[\Override]
    public function removeBootloader(string $componentName): void
    {
        $this->validateComponent($componentName);
        
        $file                       = $this->bootloaderDir.'/'.$componentName.'.ini';
        
        if(false === file_exists($file)) {
            throw new PackageNotFound($componentName);
        }
        
        Safe::execute(fn() => unlink($file));
    }
    
    protected function validateComponent(string $componentName): void
    {
        if(preg_match('/[^a-z0-9_]/', $componentName)) {
            throw new BootloaderException('Invalid component name: '.$componentName);
        }
    }
    
    protected function generateBootloaderContent(array $data): string
    {
        $now                        = date('Y-m-d H:i:s');
        $header                    = <<<INI
; ========================================================
; This file is generated by the BootManager at $now
; Do not edit manually
; ========================================================
INI;
        
        return $header.$this->arrayToIni($data);
    }
    
    protected function arrayToIni(array $data): string
    {
        $ini                        = [];
        
        foreach ($data as $key => $value) {
            if(is_array($value)) {
                foreach ($value as $subValue) {
                    $ini[] = $key.'[] = '.$this->valueToIni($subValue);
                }
                
                $ini[]              = '';
            } else {
                $ini[]              = $key.' = '.$this->valueToIni($value);
            }
        }
        
        return implode(PHP_EOL, $ini);
    }
    
    protected function valueToIni(mixed $value): string
    {
        if(is_int($value) || is_float($value)) {
            return (string)$value;
        }
        
        if(is_bool($value)) {
            return $value ? 'true' : 'false';
        }
        
        return '"'.$value.'"';
    }
    
}